msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)msg = "My nickname is Bam"
msg = "my pet name is Hengheng "
print(msg)
